local LSM = LibStub("LibSharedMedia-3.0")
local koKR, ruRU, zhCN, zhTW, western = LSM.LOCALE_BIT_koKR, LSM.LOCALE_BIT_ruRU, LSM.LOCALE_BIT_zhCN, LSM.LOCALE_BIT_zhTW, LSM.LOCALE_BIT_western

LSM:Register("font","ABF", [[Interface\Addons\ShamanAuras2\Media\fonts\ABF.ttf]])
LSM:Register("font","Accidental Presidency", [[Interface\Addons\Skada\media\fonts\Accidental_Presidency.ttf]])
LSM:Register("font","Action Man", [[Interface\Addons\ShamanAuras2\Media\fonts\Action_Man.ttf]])
LSM:Register("font","Adeventure", [[Interface\Addons\ShamanAuras2\Media\fonts\Adventure.ttf]])
LSM:Register("font","Arial", [[Interface\Addons\Skada\media\fonts\Arial.ttf]])
LSM:Register("font","Avqest", [[Interface\Addons\ShamanAuras2\Media\fonts\Avqest.ttf]])
LSM:Register("font","Continuum Medium", [[Interface\Addons\ShamanAuras2\Media\fonts\Continuum_Medium.ttf]])
LSM:Register("font","DejaVu Sans",[[Interface\Addons\ShamanAuras2\Media\fonts\deja_vu\DejaVuLGCSans.ttf]],ruRU + western)
LSM:Register("font","DejaVu Serif",[[Interface\Addons\ShamanAuras2\Media\fonts\deja_vu\DejaVuLGCSerif.ttf]],ruRU + western)
LSM:Register("font","Die Die Die!", [[Interface\Addons\ShamanAuras2\Media\fonts\DieDieDie.ttf]])
LSM:Register("font","Expressway", [[Interface\Addons\ShamanAuras2\Media\fonts\Expressway.ttf]])
LSM:Register("font","Fira Mono Medium", [[Interface\Addons\ShamanAuras2\Media\fonts\FiraMono-Medium.ttf]])
LSM:Register("font","Gentium Plus",[[Interface\Addons\ShamanAuras2\Media\fonts\gentium_plus\GentiumPlus-R.ttf]],ruRU + western)
LSM:Register("font","Homespun", [[Interface\Addons\ShamanAuras2\Media\fonts\Homespun.ttf]])
LSM:Register("font","Liberation Sans",[[Interface\Addons\ShamanAuras2\Media\fonts\liberation\LiberationSans-Regular.ttf]],ruRU + western)
LSM:Register("font","Liberation Serif",[[Interface\Addons\ShamanAuras2\Media\fonts\liberation\LiberationSerif-Regular.ttf]],ruRU + western)
LSM:Register("font","PT Sans Narrow", [[Interface\Addons\ShamanAuras2\Media\fonts\PT_Sans_Narrow.ttf]])
LSM:Register("font","VeraSe", [[Interface\Addons\ShamanAuras2\Media\fonts\VeraSe.ttf]])
LSM:Register("font","WenQuanYi Zen Hei",[[Interface\Addons\ShamanAuras2\Media\fonts\wen_quan_yi_zen_hei\wqy-zenhei.ttf]],koKR + ruRU + zhCN + zhTW + western)
LSM:Register("statusbar","Aluminium", [[Interface\Addons\ShamanAuras2\Media\statusbar\Aluminium]])
LSM:Register("statusbar","Armory", [[Interface\Addons\ShamanAuras2\Media\statusbar\Armory]])
LSM:Register("statusbar","Banto Bar", [[Interface\Addons\ShamanAuras2\Media\statusbar\BantoBar]])
LSM:Register("statusbar","Cilo", [[Interface\Addons\ShamanAuras2\Media\statusbar\Cilo]])
LSM:Register("statusbar","Eighths", [[Interface\Addons\ShamanAuras2\Media\statusbar\Eighths]])
LSM:Register("statusbar","Fifths", [[Interface\Addons\ShamanAuras2\Media\statusbar\Fifths]])
LSM:Register("statusbar","Flat", [[Interface\Addons\ShamanAuras2\Media\statusbar\Flat]])
LSM:Register("statusbar","Fourths", [[Interface\Addons\ShamanAuras2\Media\statusbar\Fourths]])
LSM:Register("statusbar","Frost", [[Interface\Addons\ShamanAuras2\Media\statusbar\Frost]])
LSM:Register("statusbar","Glamour", [[Interface\Addons\ShamanAuras2\Media\statusbar\Glamour]])
LSM:Register("statusbar","Glamour2", [[Interface\Addons\ShamanAuras2\Media\statusbar\Glamour2]])
LSM:Register("statusbar","Glamour3", [[Interface\Addons\ShamanAuras2\Media\statusbar\Glamour3]])
LSM:Register("statusbar","Glamour4", [[Interface\Addons\ShamanAuras2\Media\statusbar\Glamour4]])
LSM:Register("statusbar","Glamour5", [[Interface\Addons\ShamanAuras2\Media\statusbar\Glamour5]])
LSM:Register("statusbar","Glamour6", [[Interface\Addons\ShamanAuras2\Media\statusbar\Glamour6]])
LSM:Register("statusbar","Glamour7", [[Interface\Addons\ShamanAuras2\Media\statusbar\Glamour7]])
LSM:Register("statusbar","Glaze2", [[Interface\Addons\ShamanAuras2\Media\statusbar\Glaze2]])
LSM:Register("statusbar","Gloss", [[Interface\Addons\ShamanAuras2\Media\statusbar\Gloss]])
LSM:Register("statusbar","Graphite", [[Interface\Addons\ShamanAuras2\Media\statusbar\Graphite]])
LSM:Register("statusbar","Grid", [[Interface\Addons\ShamanAuras2\Media\statusbar\Grid]])
LSM:Register("statusbar","Halves", [[Interface\Addons\ShamanAuras2\Media\statusbar\Halves]])
LSM:Register("statusbar","Healbot", [[Interface\Addons\ShamanAuras2\Media\statusbar\Healbot]])
LSM:Register("statusbar","Lite Step", [[Interface\Addons\ShamanAuras2\Media\statusbar\LiteStep]])
LSM:Register("statusbar","Minimalist", [[Interface\Addons\ShamanAuras2\Media\statusbar\Minimalist]])
LSM:Register("statusbar","Otravi", [[Interface\Addons\ShamanAuras2\Media\statusbar\Otravi]])
LSM:Register("statusbar","Outline", [[Interface\Addons\ShamanAuras2\Media\statusbar\Outline]])
LSM:Register("statusbar","Perl", [[Interface\Addons\ShamanAuras2\Media\statusbar\Perl]])
LSM:Register("statusbar","Rocks", [[Interface\Addons\ShamanAuras2\Media\statusbar\Rocks]])
LSM:Register("statusbar","Round", [[Interface\Addons\ShamanAuras2\Media\statusbar\Round]])
LSM:Register("statusbar","Runes", [[Interface\Addons\ShamanAuras2\Media\statusbar\Runes]])
LSM:Register("statusbar","Smooth", [[Interface\Addons\ShamanAuras2\Media\statusbar\Smooth]])
LSM:Register("statusbar","Tenths", [[Interface\Addons\ShamanAuras2\Media\statusbar\Tenths]])
LSM:Register("statusbar","Whole", [[Interface\Addons\ShamanAuras2\Media\statusbar\Whole]])
LSM:Register("statusbar","Xeon", [[Interface\Addons\ShamanAuras2\Media\statusbar\Xeon]])
